### ISSUE TITLE
stat interrupt should fire only on the rising edge of its enable flags

### ISSUE THREAD

**Issue by emrsmsrli** [emrsmsrli/gameboi#3]
we're firing `interrupt::stat` everytime `stat_.mode_interrupt_enabled()` or `stat_.coincidence_interrupt_set()` returns true. this only needs to be once.

**Comment by aknkrstozkn** [comment]
https://www.youtube.com/watch?v=rR4n-0KYeKQ

Emre <notifications@github.com>, 27 Şub 2020 Per, 14:06 tarihinde şunu
yazdı:
